site_name: Voltarium Python Client
site_description: Asynchronous Python client for CCEE (Brazilian Electric Energy Commercialization Chamber) API
site_url: https://joaodaher.github.io/voltarium-python
repo_url: https://github.com/joaodaher/voltarium-python
repo_name: joaodaher/voltarium-python
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.sections
    - toc.integrate
    - content.action.edit
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - tables

nav:
  - Welcome: index.md
  - About: about.md
  - Supported Endpoints: endpoints.md
  - Examples: examples.md
  - Staging: staging.md
